-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.consumo_anual
(
    id_consumo integer NOT NULL,
    id_paises integer NOT NULL,
    ano integer NOT NULL,
    porcentagem integer NOT NULL,
    tipo_energia integer NOT NULL,
    CONSTRAINT consumo_anual_pkey PRIMARY KEY (id_consumo)
);

CREATE TABLE IF NOT EXISTS public.continente
(
    id_continente integer NOT NULL,
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT continente_pkey PRIMARY KEY (id_continente)
);

CREATE TABLE IF NOT EXISTS public.emissao_g_efeito_estufa
(
    id_emissao integer NOT NULL,
    id_paises integer NOT NULL,
    ano integer NOT NULL,
    quantidade_emitida bigint NOT NULL,
    CONSTRAINT emissao_g_efeito_estufa_pkey PRIMARY KEY (id_emissao)
);

CREATE TABLE IF NOT EXISTS public.fonte_energia
(
    id_fonte_energia integer NOT NULL,
    nome character varying(50)[] COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT fonte_energia_pkey PRIMARY KEY (id_fonte_energia)
);

CREATE TABLE IF NOT EXISTS public.paises
(
    id_paises integer NOT NULL,
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    fundacao integer NOT NULL,
    continente integer NOT NULL,
    CONSTRAINT paises_pkey PRIMARY KEY (id_paises)
);

CREATE TABLE IF NOT EXISTS public.populacao
(
    id_pop integer NOT NULL,
    id_paises integer NOT NULL,
    ano integer NOT NULL,
    quantidade_hab integer NOT NULL,
    CONSTRAINT populacao_pkey PRIMARY KEY (id_pop)
);

ALTER TABLE IF EXISTS public.consumo_anual
    ADD CONSTRAINT consumo_anual_id_paises_fkey FOREIGN KEY (id_paises)
    REFERENCES public.paises (id_paises) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.consumo_anual
    ADD CONSTRAINT consumo_anual_tipo_energia_fkey FOREIGN KEY (tipo_energia)
    REFERENCES public.fonte_energia (id_fonte_energia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.emissao_g_efeito_estufa
    ADD CONSTRAINT emissao_g_efeito_estufa_id_paises_fkey FOREIGN KEY (id_paises)
    REFERENCES public.paises (id_paises) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.paises
    ADD CONSTRAINT paises_continente_fkey FOREIGN KEY (continente)
    REFERENCES public.continente (id_continente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.populacao
    ADD CONSTRAINT populacao_id_paises_fkey FOREIGN KEY (id_paises)
    REFERENCES public.paises (id_paises) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;